apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-resourcemanager
  labels:
    app: hadoop
    unit: namenode
data:
  HADOOP_DAEMONS: |
    resourcemanager
  DFS_NAMENODE_HOSTNAME: "hadoop-namenode-0.hadoop"
  YARN_SCHEDULER_MINIMUM_ALLOCATION_MB: "128"
  YARN_SCHEDULER_MAXIMUM_ALLOCATION_MB: "1536"