version: "3"
services:
  namenode:
    image: mpolatcan/hadoop-dev:3.2.1-java8
    container_name: namenode
    hostname: namenode
    environment:
      - HADOOP_DAEMONS=
          namenode
          nodemanager
    ports:
      - 9870:9870

  secondarynamenode:
    image: mpolatcan/hadoop-dev:3.2.1-java8
    container_name: secondarynamenode
    hostname: secondarynamenode
    environment:
      - HADOOP_DAEMONS=
          secondarynamenode
    ports:
      - 9868:9868

  resourcemanager:
    image: mpolatcan/hadoop-dev:3.2.1-java8
    container_name: resourcemanager
    hostname: resourcemanager
    environment:
      - HADOOP_DAEMONS=
          resourcemanager
    ports:
      - 8088:8088

  datanode:
    image: mpolatcan/hadoop:3.2.1-java8
    environment:
      - HADOOP_DAEMONS=
          datanode
          nodemanager
      - FS_HOSTNAME=namenode
      - YARN_NODEMANAGER_RESOURCE_MEMORY_MB=1536
      - YARN_NODEMANAGER_RESOURCE_CPU_VCORES=2
      - YARN_RESOURCEMANAGER_HOSTNAME=resourcemanager
    links:
      - namenode
    ports:
      - 9864
