# Written by Mutlu Polatcan
# 18.11.2019
# TODO Liveness and Readiness probes will be added
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-master
  labels:
    app: hadoop
    type: master
spec:
  serviceName: hadoop
  replicas: 1
  selector:
    matchLabels:
      app: hadoop
      type: master
  template:
    metadata:
      name: hadoop-master
      labels:
        app: hadoop
        type: master
    spec:
      initContainers:
        - name: init-hadoop
          imagePullPolicy: Always
          image: mpolatcan/hadoop:3.2.1-java8
          command:
            - /bin/bash
          args:
            - -c
            - $(INIT_SCRIPT)
          envFrom:
            - configMapRef:
                name: hadoop-init
          volumeMounts:
            - mountPath: /hadoop-state
              name: hadoop-volume
      containers:
        - name: hadoop-master
          imagePullPolicy: Always
          image: mpolatcan/hadoop:3.2.1-java8
          envFrom:
            - configMapRef:
                name: hadoop-master
          volumeMounts:
            - mountPath: /home/hduser
              name: hadoop-volume
          livenessProbe:
            httpGet:
              path: /
              port: 9870
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 9870
            initialDelaySeconds: 5
            periodSeconds: 5
      securityContext:
        fsGroup: 1000
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: hadoop-volume
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gce-pd-hdd
        resources:
          requests:
            storage: 50Gi