# Written by Mutlu Polatcan
# 18.11.2019
apiVersion: v1
kind: Service
metadata:
  name: hadoop-datanode-webapps
  labels:
    app: hadoop
    unit: datanode
spec:
  selector:
    app: hadoop
    unit: datanode
  ports:
    - port: 9864 # Datanode HTTP Port
      name: dn-http-port
    - port: 9865 # Datanode HTTPS Port
      name: dn-https-port
  type: NodePort