# Written by Mutlu Polatcan
# 18.11.2019
apiVersion: v1
kind: Service
metadata:
  name: hadoop-nodemanager-webapps
  labels:
    app: hadoop
    unit: nodemanager
spec:
  selector:
    app: hadoop
    unit: nodemanager
  ports:
    - port: 8042 # YARN Nodemanager HTTP Port
      name: nm-http-port
    - port: 8044 # YARN Nodemanager HTTPS Port
      name: nm-https-port
  type: NodePort