version: "3"
services:
  resourcemanager:
    image: mpolatcan/hadoop:3.2.1-java8
    container_name: resourcemanager
    hostname: resourcemanager
    environment:
      HADOOP_DAEMONS: |
          resourcemanager
      FS_HOSTNAME: namenode
      YARN_SCHEDULER_MINIMUM_ALLOCATION_MB: 128
      YARN_SCHEDULER_MAXIMUM_ALLOCATION_MB: 1536
    ports:
      - 8088:8088

  nodemanager:
    image: mpolatcan/hadoop:3.2.1-java8
    environment:
      HADOOP_DAEMONS: |
          nodemanager
      FS_HOSTNAME: namenode
      YARN_RESOURCEMANAGER_HOSTNAME: resourcemanager
      YARN_NODEMANAGER_RESOURCE_MEMORY_MB: 1536
      YARN_NODEMANAGER_RESOURCE_CPU_VCORES: 2
    ports:
      - 8042

  namenode:
    image: mpolatcan/hadoop:3.2.1-java8
    container_name: namenode
    hostname: namenode
    environment:
      HADOOP_DAEMONS: |
          namenode
      DFS_NAMENODE_RPC_BIND_HOST: "NULL"
    ports:
      - 9870:9870

  secondarynamenode:
    image: mpolatcan/hadoop:3.2.1-java8
    container_name: secondarynamenode
    hostname: secondarynamenode
    environment:
      HADOOP_DAEMONS: |
          secondarynamenode
      FS_HOSTNAME: namenode
    ports:
      - 9868:9868

  datanode:
    image: mpolatcan/hadoop:3.2.1-java8
    environment:
      HADOOP_DAEMONS: |
          datanode
      FS_HOSTNAME: namenode
      DFS_NAMENODE_HOSTNAME: namenode
    ports:
      - 9864