# Written by Mutlu Polatcan
# 18.11.2019
# TODO PersistentVolume and Persistent Volume Claims
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-master
  labels:
    app: hadoop
    type: master
spec:
  serviceName: hadoop
  replicas: 1
  selector:
    matchLabels:
      app: hadoop
      type: master
  template:
    metadata:
      name: hadoop-master
      labels:
        app: hadoop
        type: master
    spec:
      containers:
        - name: hadoop-master
          imagePullPolicy: Always
          image: mpolatcan/hadoop:3.2.1-java8
          envFrom:
            - configMapRef:
                name: hadoop-master
      restartPolicy: Always