version: "3"
services:
  master:
    image: mpolatcan/hadoop:3.1.4-java8
    container_name: master
    hostname: master
    environment:
      HADOOP_DAEMONS: |
        namenode
        secondarynamenode
        resourcemanager
        timelineserver
      FS_DEFAULTFS: "hdfs://master:9000"
      YARN_RESOURCEMANAGER_HOSTNAME: "master"
      YARN_SCHEDULER_MINIMUM_ALLOCATION_MB: "128"
      YARN_SCHEDULER_MAXIMUM_ALLOCATION_MB: "4096"
      TEZ_ENABLED: "true"
      TEZ_HISTORY_LOGGING_SERVICE_CLASS: "org.apache.tez.dag.history.logging.ats.ATSHistoryLoggingService"
      TEZ_TEZ_UI_HISTORY_URL_BASE: "http://tez-ui:8080/tez/"
      YARN_TIMELINE_SERVICE_ENABLED: "true"
      YARN_TIMELINE_SERVICE_HOSTNAME: "master"
      YARN_TIMELINE_SERVICE_HTTP_CROSS_ORIGIN_ENABLED: "true"
      YARN_SYSTEM_METRICS_PUBLISHER_ENABLED: "true"
      YARN_NODEMANAGER_VMEM_PMEM_RATIO: "3"
      TEZ_USE_CLUSTER_HADOOP_LIBS: "true"
      MAPREDUCE_MAP_MEMORY_MB: "4096"
      MAPREDUCE_REDUCE_MEMORY_MB: "4096"
    ports:
      - 9870:9870 # Namenode UI
      - 9868:9868 # Secondarynamenode UI Port
      - 8088:8088 # Resourcemanager UI Port
      - 8188:8188 # Timelineserver Port

  slave:
    image: mpolatcan/hadoop:3.1.4-java8
    environment:
      HADOOP_DAEMONS: |
        datanode
        nodemanager
      FS_DEFAULTFS: "hdfs://master:9000"
      YARN_RESOURCEMANAGER_HOSTNAME: "master"
      YARN_NODEMANAGER_RESOURCE_MEMORY_MB: "4096"
      YARN_NODEMANAGER_RESOURCE_CPU_VCORES: "2"
      TEZ_HISTORY_LOGGING_SERVICE_CLASS: "org.apache.tez.dag.history.logging.ats.ATSHistoryLoggingService"
      TEZ_TEZ_UI_HISTORY_URL_BASE: "http://tez-ui:8080/tez/"
      YARN_TIMELINE_SERVICE_ENABLED: "true"
      YARN_TIMELINE_SERVICE_HOSTNAME: "master"
      YARN_TIMELINE_SERVICE_HTTP_CROSS_ORIGIN_ENABLED: "true"
      YARN_SYSTEM_METRICS_PUBLISHER_ENABLED: "true"
      TEZ_USE_CLUSTER_HADOOP_LIBS: "true"
      MAPREDUCE_MAP_MEMORY_MB: "4096"
      MAPREDUCE_REDUCE_MEMORY_MB: "4096"
      YARN_NODEMANAGER_VMEM_PMEM_RATIO: "3"
    ports:
      - 9864 # Datanode UI Port
      - 8042 # Nodemanager UI Port
    depends_on:
      - master

  tez-ui:
    image: mpolatcan/tez-ui:0.9.2
    container_name: tez-ui
    hostname: tez-ui
    environment:
      YARN_TIMELINE_SERVER_HOSTNAME: "localhost"
      YARN_RESOURCEMANAGER_HOSTNAME: "master"
    ports:
      - 8080:8080