# Written by Mutlu Polatcan
# 21.11.2019
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-resourcemanager
  labels:
    app: hadoop
    unit: resourcemanager
spec:
  serviceName: hadoop
  replicas: 1
  selector:
    matchLabels:
      app: hadoop
      unit: resourcemanager
  template:
    metadata:
      labels:
        app: hadoop
        unit: resourcemanager
    spec:
      initContainers:
        - name: hadoop-init
          image: mpolatcan/hadoop:3.2.1-java8
          imagePullPolicy: Always
          command:
            - /bin/bash
          args:
            - -c
            - $(INIT_SCRIPT)
          envFrom:
            - configMapRef:
                name: hadoop-init
          volumeMounts:
            - mountPath: /hadoop-state
              name: hadoop-volume
      containers:
        - name: hadoop-nodemanager
          image: mpolatcan/hadoop:3.2.1-java8
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: hadoop-resourcemanager
          volumeMounts:
            - mountPath: /home/hduser
              name: hadoop-volume
          livenessProbe:
            httpGet:
              path: /
              port: 8088
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8088
            initialDelaySeconds: 5
            periodSeconds: 5
      securityContext:
        fsGroup: 1000
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: hadoop-volume
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gce-pd-hdd
        resources:
          requests:
            storage: 50Gi

