apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hadoop
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: hadoop-master-webapp
              servicePort: rm-http-port