# Written by Mutlu Polatcan
# 21.11.2019
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-nodemanager
  labels:
    app: hadoop
    unit: nodemanager
spec:
  serviceName: hadoop
  replicas: 1
  selector:
    matchLabels:
      app: hadoop
      unit: nodemanager
  template:
    metadata:
      labels:
        app: hadoop
        unit: nodemanager
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - hadoop
                  - key: unit
                    operator: In
                    values:
                      - resourcemanager
                      - nodemanager
              topologyKey: kubernetes.io/hostname
      initContainers:
        - name: hadoop-init
          image: mpolatcan/hadoop:3.2.1-java8
          imagePullPolicy: Always
          command:
            - /bin/bash
          args:
            - -c
            - $(INIT_SCRIPT)
          envFrom:
            - configMapRef:
                name: hadoop-init
          volumeMounts:
            - mountPath: /hadoop-state
              name: hadoop-nm-volume
      containers:
        - name: hadoop-nodemanager
          image: mpolatcan/hadoop:3.2.1-java8
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: hadoop-nodemanager
          volumeMounts:
            - mountPath: /home/hduser
              name: hadoop-nm-volume
          livenessProbe:
            tcpSocket:
              port: 8042
            initialDelaySeconds: 15
            periodSeconds: 2
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8042
            initialDelaySeconds: 15
            periodSeconds: 2
            failureThreshold: 3
      securityContext:
        fsGroup: 1000
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: hadoop-nm-volume
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gce-pd-hdd
        resources:
          requests:
            storage: 50Gi