version: "3"
services:
  zk1:
    image: zookeeper
    restart: always
    hostname: zk1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181

  zk2:
    image: zookeeper
    restart: always
    hostname: zk2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zk3:2888:3888;2181

  zk3:
    image: zookeeper
    restart: always
    hostname: zk3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181

  nn1:
    image: mpolatcan/hadoop:3.3.0-java8
    container_name: nn1
    hostname: nn1
    environment:
      HADOOP_DAEMONS: |
        namenode
        zkfc
      HADDOP_INITIALIZE_HA_STATE_IN_ZK: "true"
    env_file:
      - config.env
    ports:
      - 9870

  nn2:
    image: mpolatcan/hadoop:3.3.0-java8
    container_name: nn2
    hostname: nn2
    environment:
      HADOOP_DAEMONS: |
        namenode
        zkfc
      HADOOP_FORMAT_NAMENODE: "false"
      HADOOP_BOOTSTRAP_STANDBY_NAMENODE: "true"
    env_file:
      - config.env
    ports:
      - 9870

  jn1:
    image: mpolatcan/hadoop:3.3.0-java8
    container_name: jn1
    hostname: jn1
    environment:
      HADOOP_DAEMONS: |
        journalnode
    env_file:
      - config.env

  jn2:
    image: mpolatcan/hadoop:3.3.0-java8
    container_name: jn2
    hostname: jn2
    environment:
      HADOOP_DAEMONS: |
        journalnode
    env_file:
      - config.env

  datanode:
    image: mpolatcan/hadoop:3.3.0-java8
    environment:
      HADOOP_DAEMONS: |
        datanode
    env_file:
      - config.env
