name: hadoop-docker

on:
  push:
    branches:
      - master

jobs:
  build-base-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [hadoop]
        java_version: [8]
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - run: docker build -q
          -t ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-java${{matrix.java_version}}
          --build-arg JAVA_VERSION=${{matrix.java_version}}
          src/base
      - run: docker push ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-java${{matrix.java_version}}
      - run: docker rmi ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-java${{matrix.java_version}}

  build-setup-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [hadoop]
        java_version: [8]
        hadoop_version: [3.3.0, 3.2.1, 3.1.4, 2.10.1, 2.9.2, 2.8.5, 2.7.7]
        tez_version: [0.9.2]
        aws_sdk_java_version: [1.11.881]
    needs: build-base-image
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests beautifulsoup4
      - run: |
          cd src/setup
          python hadoop_config_loader_generator.py ${{matrix.hadoop_version}} ${{matrix.tez_version}}
      - run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - run: docker build -q
          -t ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.hadoop_version}}-java${{matrix.java_version}}
          --build-arg HADOOP_VERSION=${{matrix.hadoop_version}}
          --build-arg TEZ_VERSION=${{matrix.tez_version}}
          --build-arg AWS_SDK_JAVA_VERSION=${{matrix.aws_sdk_java_version}}
          --build-arg JAVA_VERSION=${{matrix.java_version}}
          src/setup
      - run: docker push ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.hadoop_version}}-java${{matrix.java_version}}
      - run: docker rmi ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.hadoop_version}}-java${{matrix.java_version}}